In [44]:
import numpy as np
import pandas as pd

In [45]:
a = np.arange(20, dtype=np.float64)

In [46]:
a = a.reshape(5, 4)

In [47]:
print(a)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [16. 17. 18. 19.]]


In [48]:
a[1,1]= np.nan
print(a)

[[ 0.  1.  2.  3.]
 [ 4. nan  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [16. 17. 18. 19.]]


In [59]:
b =np.append(a, [np.nan, np.nan, np.nan, np.nan, np.nan])
c = b.reshape(5,5)
c.shape


(5, 5)

In [60]:
df = pd.DataFrame(c, columns=['a', 'b', 'c', 'd', 'e'])

In [62]:
df

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   NaN   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0
4   NaN   NaN   NaN   NaN   NaN

In [67]:
print(df.isna())

       a      b      c      d      e
0  False  False  False  False  False
1   True  False  False  False  False
2  False  False  False  False  False
3  False  False  False  False  False
4   True   True   True   True   True


In [65]:
cleaned = df.dropna(axis=0, how='all')

In [66]:
cleaned

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   NaN   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0